### ISSUE TITLE
로그인_로그아웃

### ISSUE THREAD

**Issue by seung-woo-ryu** [seung-woo-ryu/woostagram#11]
# ToDo

- [x] repository에 findyByEmailAndPassword() 메소드, Test 코드 작성
- [x] LoginDto 생성하기
- [x] service에 userNotFounException 만들고 Handler에 추가하기. Test 코드 작성
- [x] controller에 세션 저장 후 리턴하는 부분. Test 코드 작성.

### 기능

- 로그인 관련 컨트롤러 기능
    - Post, /login
    - LoginDto 검증하는(이메일 양식, 패스워드 양식) @validation 추가 해야함.
    - UserService.login 호출하여 반환된 멤버 세션에 저장하면서 return ApiResult(success)
- 로그인 관련 서비스 기능
    - 레포지토리.findByEmailAndPassword로 유저존재하는지 확인.
    - 유저 존재하면 return user
    - 유저 존재하지 않으면 throw userNotFoundException
- 로그인 관련 레포지토리 기능
    - user 레포지토리.findByEmailAndPassword(String email, String password)

### 로직

1 - 로그인 요청

&nbsp; 1 - UserController에서 아래 2번 서비스 기능 요청. (Post, /login, @RequestBody @Valid loginDto. 이메일, 패스워드 검증 필요.)
&nbsp; 2 - UserService에서 아래 3번 메소드 불러와서 존재하는지 판별 후 return . (return boolean)
&nbsp; 3 - 레포지토리에서 유저가 존재하는지 db에 쿼리 날리는 메소드 (boolean)

2.Case1 - 로그인 성공

&nbsp; 1 - 컨트롤러에서 session 생성해서 브라우저로 반환

```jsx
{
	success: true,
	response: [],
	error: null
}
```

2.Case2 - 로그인 실패 

&nbsp; 1 - 서비스에서 UserNotFoundException(임시 네이밍) 던지고 

&nbsp; 2 - GeneralExceptionHandler에서 return ApiResult(error)

```jsx
{
	success: false,
	response: [],
	error: {
		status: 400,
		message: 유저 정보가 일치하지 않습니다,
		fieldErrors: [{
                             field: email
                             value: ~~@naver.com
                             reason: 일치하는 메일이 없습니다.},
                             ...
                                     
		}]
	}
}
```

# 로그인 체크 추가 필요

- 로그인된 상태로 기능을 수행해야하는 것들(Post 추가하기, 좋아요 누르기) 때문에 필요
- 인터셉터 활용해서 브라우저의 쿠키 확인하여 세션아이디가 존재하는지 안하는지 확인. (필터로 해도 되는데 일단은 인터셉터로, 추후에 security 사용할거라 나중에 확장)

**Comment by seung-woo-ryu** [comment]
# 로그인 체크 인터셉터 추가
### 로그인 체크 실패 에러
```jsx
{
	success: fail,
	response: [],
	error: {
		status: 401,
		message: Unauthorized,
		fieldErrors: []
	}
}
```

**Comment by seung-woo-ryu** [comment]
pr: #19
